version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    container_name: storeapp-postgres
    environment:
      POSTGRES_DB: storedb
      POSTGRES_USER: storeuser
      POSTGRES_PASSWORD: pgStore@1
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
